version: 2

jobs:
  big_integer_test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
          - gradle-{{ checksum "~/project/BigInteger/build.gradle" }}
          - gradle-
      - run:
          name: BigInteger Test
          working_directory: ~/project/BigInteger
          command: gradle test
      - store_artifacts:
          path: ~/project/BigInteger/build/reports/tests/test
          destination: test
      - save_cache:
          key: gradle-{{ checksum "~/project/BigInteger/build.gradle" }}
          paths:
            - ~/project/.gradle
  big_integer_deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: BigInteger Deploy
          working_directory: ~/project/BigInteger/src/main/java
          command: zip src.zip *.java
      - store_artifacts:
          path: ~/project/BigInteger/src/main/java/src.zip
          destination: BigInteger.zip

  movie_database_test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
          - gradle-{{ checksum "~/project/MovieDatabase/build.gradle" }}
          - gradle-
      - run:
          name: MovieDatabase Test
          working_directory: ~/project/MovieDatabase
          command: gradle test
      - store_artifacts:
          path: ~/project/MovieDatabase/build/reports/tests/test
          destination: test
      - save_cache:
          key: gradle-{{ checksum "~/project/MovieDatabase/build.gradle" }}
          paths:
            - ~/project/.gradle
  movie_database_deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: MovieDatabase Deploy
          working_directory: ~/project/MovieDatabase/src/main/java
          command: zip src.zip *.java
      - store_artifacts:
          path: ~/project/MovieDatabase/src/main/java/src.zip
          destination: MovieDatabase.zip

  stack_calculator_test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
          - gradle-{{ checksum "~/project/StackCalculator/build.gradle" }}
          - gradle-
      - run:
          name: StackCalculator Test
          working_directory: ~/project/StackCalculator
          command: gradle test
      - store_artifacts:
          path: ~/project/StackCalculator/build/reports/tests/test
          destination: test
      - save_cache:
          key: gradle-{{ checksum "~/project/StackCalculator/build.gradle" }}
          paths:
            - ~/project/.gradle
  stack_calculator_deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: StackCalculator Deploy
          working_directory: ~/project/StackCalculator/src/main/java
          command: zip src.zip *.java
      - store_artifacts:
          path: ~/project/StackCalculator/src/main/java/src.zip
          destination: StackCalculator.zip

  matching_test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
          - gradle-{{ checksum "~/project/Matching/build.gradle" }}
          - gradle-
      - run:
          name: Matching Test
          working_directory: ~/project/Matching
          command: gradle test
      - store_artifacts:
          path: ~/project/Matching/build/reports/tests/test
          destination: test
      - save_cache:
          key: gradle-{{ checksum "~/project/Matching/build.gradle" }}
          paths:
            - ~/project/.gradle
  matching_deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Matching Deploy
          working_directory: ~/project/Matching/src/main/java
          command: zip src.zip *.java
      - store_artifacts:
          path: ~/project/Matching/src/main/java/src.zip
          destination: Matching.zip

workflows:
  version: 2

  big_integer:
    jobs:
      - big_integer_test:
          filters:
            branches:
              only:
                - master
                - big-integer
      - big_integer_deploy:
          requires:
            - big_integer_test
          filters:
            branches:
              only:
                - master
                - big-integer

  movie_database:
    jobs:
      - movie_database_test:
          filters:
            branches:
              only:
                - master
                - movie-database
      - movie_database_deploy:
          requires:
            - movie_database_test
          filters:
            branches:
              only:
                - master
                - movie-database

  stack_calculator:
    jobs:
      - stack_calculator_test:
          filters:
            branches:
              only:
                - master
                - stack-calculator
      - stack_calculator_deploy:
          requires:
            - stack_calculator_test
          filters:
            branches:
              only:
                - master
                - stack-calculator

  matching:
    jobs:
      - matching_test:
          filters:
            branches:
              only:
                - master
                - matching
      - matching_deploy:
          requires:
            - matching_test
          filters:
            branches:
              only:
                - master
                - matching
